// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Album → Photos*
 */
export interface AlbumDocumentDataPhotosItem {
  /**
   * Photo field in *Album → Photos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: album.photos[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;
}

/**
 * Content for Album documents
 */
interface AlbumDocumentData {
  /**
   * Album Name field in *Album*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: album.album_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  album_name: prismic.KeyTextField;

  /**
   * description field in *Album*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: album.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Image field in *Album*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: album.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Secondary Image field in *Album*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: album.secondary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  secondary_image: prismic.ImageField<never>;

  /**
   * Photos field in *Album*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: album.photos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  photos: prismic.GroupField<Simplify<AlbumDocumentDataPhotosItem>>;
}

/**
 * Album document from Prismic
 *
 * - **API ID**: `album`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AlbumDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AlbumDocumentData>, "album", Lang>;

type ExecPageDocumentDataSlicesSlice =
  | HeaderSlice
  | CoachingTeamSlice
  | ExecPageSlice;

/**
 * Content for Exec Page documents
 */
interface ExecPageDocumentData {
  /**
   * Slice Zone field in *Exec Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExecPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Exec Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: exec_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Exec Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: exec_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Exec Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Exec Page document from Prismic
 *
 * - **API ID**: `exec_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExecPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ExecPageDocumentData>,
    "exec_page",
    Lang
  >;

type GalleryDocumentDataSlicesSlice =
  | FooterSlice
  | AlbumOnGallerySlice
  | HeaderSlice;

/**
 * Content for Gallery documents
 */
interface GalleryDocumentData {
  /**
   * Slice Zone field in *Gallery*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GalleryDocumentDataSlicesSlice> /**
   * Meta Title field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: gallery.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: gallery.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | GalleryOnHomeSlice
  | FooterSlice
  | InfoSlice
  | CalendarSlice
  | AboutUsSlice
  | BigHeaderSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MerchDocumentDataSlicesSlice =
  | InfoSlice
  | MerchPhotosSlice
  | FooterSlice
  | HeaderSlice;

/**
 * Content for Merch documents
 */
interface MerchDocumentData {
  /**
   * Slice Zone field in *Merch*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: merch.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MerchDocumentDataSlicesSlice> /**
   * Meta Title field in *Merch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: merch.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Merch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: merch.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Merch*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: merch.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Merch document from Prismic
 *
 * - **API ID**: `merch`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MerchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MerchDocumentData>, "merch", Lang>;

/**
 * Item in *Navbar → links to social*
 */
export interface NavbarDocumentDataLinksToSocialItem {
  /**
   * link field in *Navbar → links to social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.links_to_social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link type field in *Navbar → links to social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: navbar.links_to_social[].link_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  link_type: prismic.SelectField<
    "Instagram" | "Discord" | "Linktree" | "Email" | "Membership",
    "filled"
  >;
}

/**
 * Item in *Navbar → Pages*
 */
export interface NavbarDocumentDataPagesItem {
  /**
   * Page field in *Navbar → Pages*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.pages[].page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page: prismic.ContentRelationshipField<
    "gallery" | "home" | "merch" | "exec_page"
  >;

  /**
   * Display Name field in *Navbar → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.pages[].display_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  display_name: prismic.KeyTextField;

  /**
   * Sub Pages field in *Navbar → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: write the id of the sub pages as you wrote them in the page with spaces in between.
   * - **API ID Path**: navbar.pages[].sub_pages
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_pages: prismic.KeyTextField;
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * links to social field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.links_to_social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_to_social: prismic.GroupField<
    Simplify<NavbarDocumentDataLinksToSocialItem>
  >;

  /**
   * Pages field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.pages[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pages: prismic.GroupField<Simplify<NavbarDocumentDataPagesItem>>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * Title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * OG Image field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Website logo field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.website_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  website_logo: prismic.ImageField<never>;

  /**
   * bg_icon field in *settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.bg_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_icon: prismic.ImageField<never>;
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AlbumDocument
  | ExecPageDocument
  | GalleryDocument
  | HomeDocument
  | MerchDocument
  | NavbarDocument
  | SettingsDocument;

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * uid field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: about_us.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * header field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * paragraph field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Video? field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: about_us.default.primary.video_bool
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  video_bool: prismic.BooleanField;

  /**
   * Video Link field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_link: prismic.KeyTextField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>;

/**
 * Primary content in *AlbumOnGallery → Default → Primary*
 */
export interface AlbumOnGallerySliceDefaultPrimary {
  /**
   * Albums field in *AlbumOnGallery → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: album_on_gallery.default.primary.albums
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  albums: prismic.ContentRelationshipField<"album">;
}

/**
 * Default variation for AlbumOnGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlbumOnGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlbumOnGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AlbumOnGallery*
 */
type AlbumOnGallerySliceVariation = AlbumOnGallerySliceDefault;

/**
 * AlbumOnGallery Shared Slice
 *
 * - **API ID**: `album_on_gallery`
 * - **Description**: AlbumOnGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlbumOnGallerySlice = prismic.SharedSlice<
  "album_on_gallery",
  AlbumOnGallerySliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Links to Social*
 */
export interface BigHeaderSliceDefaultPrimaryLinksToSocialItem {
  /**
   * link field in *Hero → Default → Primary → Links to Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: big_header.default.primary.links_to_social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link type field in *Hero → Default → Primary → Links to Social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: big_header.default.primary.links_to_social[].link_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  link_type: prismic.SelectField<
    "Instagram" | "Linktree" | "Discord" | "Email" | "Membership "
  >;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface BigHeaderSliceDefaultPrimary {
  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_header.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: big_header.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * Links to Social field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: big_header.default.primary.links_to_social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_to_social: prismic.GroupField<
    Simplify<BigHeaderSliceDefaultPrimaryLinksToSocialItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type BigHeaderSliceVariation = BigHeaderSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `big_header`
 * - **Description**: BigHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigHeaderSlice = prismic.SharedSlice<
  "big_header",
  BigHeaderSliceVariation
>;

/**
 * Primary content in *Calendar → Default → Primary*
 */
export interface CalendarSliceDefaultPrimary {
  /**
   * uid field in *Calendar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: calendar.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Heading field in *Calendar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * info field in *Calendar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.default.primary.info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  info: prismic.RichTextField;

  /**
   * Calendar Iframe field in *Calendar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.default.primary.calendar_iframe
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calendar_iframe: prismic.KeyTextField;

  /**
   * background Image field in *Calendar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Calendar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalendarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalendarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Calendar*
 */
type CalendarSliceVariation = CalendarSliceDefault;

/**
 * Calendar Shared Slice
 *
 * - **API ID**: `calendar`
 * - **Description**: Calendar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalendarSlice = prismic.SharedSlice<
  "calendar",
  CalendarSliceVariation
>;

/**
 * Item in *CoachingTeam → Default → Primary → CoacheBio*
 */
export interface CoachingTeamSliceDefaultPrimaryCoachesItem {
  /**
   * CoachImage field in *CoachingTeam → Default → Primary → CoacheBio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coaching_team.default.primary.coaches[].coachimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  coachimage: prismic.ImageField<never>;

  /**
   * CoachName field in *CoachingTeam → Default → Primary → CoacheBio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coaching_team.default.primary.coaches[].coachname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  coachname: prismic.RichTextField;

  /**
   * CoachBio field in *CoachingTeam → Default → Primary → CoacheBio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coaching_team.default.primary.coaches[].coachbio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  coachbio: prismic.RichTextField;
}

/**
 * Primary content in *CoachingTeam → Default → Primary*
 */
export interface CoachingTeamSliceDefaultPrimary {
  /**
   * uid field in *CoachingTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: coaching_team.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Title field in *CoachingTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coaching_team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * CoacheBio field in *CoachingTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: coaching_team.default.primary.coaches[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  coaches: prismic.GroupField<
    Simplify<CoachingTeamSliceDefaultPrimaryCoachesItem>
  >;
}

/**
 * Default variation for CoachingTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoachingTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoachingTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoachingTeam*
 */
type CoachingTeamSliceVariation = CoachingTeamSliceDefault;

/**
 * CoachingTeam Shared Slice
 *
 * - **API ID**: `coaching_team`
 * - **Description**: CoachingTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoachingTeamSlice = prismic.SharedSlice<
  "coaching_team",
  CoachingTeamSliceVariation
>;

/**
 * Item in *ExecTeam → Default → Primary → execTeam*
 */
export interface ExecPageSliceDefaultPrimaryExecTeamItem {
  /**
   * execName field in *ExecTeam → Default → Primary → execTeam*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.default.primary.execTeam[].execName
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  execName: prismic.RichTextField;

  /**
   * execRole field in *ExecTeam → Default → Primary → execTeam*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.default.primary.execTeam[].execRole
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  execRole: prismic.RichTextField;

  /**
   * execImage field in *ExecTeam → Default → Primary → execTeam*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.default.primary.execTeam[].execImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  execImage: prismic.ImageField<never>;
}

/**
 * Primary content in *ExecTeam → Default → Primary*
 */
export interface ExecPageSliceDefaultPrimary {
  /**
   * uid field in *ExecTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: exec_page.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Title field in *ExecTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * execTeam field in *ExecTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: exec_page.default.primary.execTeam[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  execTeam: prismic.GroupField<
    Simplify<ExecPageSliceDefaultPrimaryExecTeamItem>
  >;
}

/**
 * Default variation for ExecTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExecPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExecPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ExecTeam*
 */
type ExecPageSliceVariation = ExecPageSliceDefault;

/**
 * ExecTeam Shared Slice
 *
 * - **API ID**: `exec_page`
 * - **Description**: ExecPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExecPageSlice = prismic.SharedSlice<
  "exec_page",
  ExecPageSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Links to Social*
 */
export interface FooterSliceDefaultPrimaryLinksToSocialItem {
  /**
   * link field in *Footer → Default → Primary → Links to Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links_to_social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link type field in *Footer → Default → Primary → Links to Social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: footer.default.primary.links_to_social[].link_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  link_type: prismic.SelectField<
    "Instagram" | "Discord" | "Email" | "Linktree" | "Membership",
    "filled"
  >;
}

/**
 * Item in *Footer → Small → Primary → Links to Social*
 */
export interface FooterSliceSmallPrimaryLinksToSocialItem {
  /**
   * link field in *Footer → Small → Primary → Links to Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.small.primary.links_to_social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * link type field in *Footer → Small → Primary → Links to Social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Instagram
   * - **API ID Path**: footer.small.primary.links_to_social[].link_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  link_type: prismic.SelectField<
    "Instagram" | "Discord" | "Email" | "Linktree" | "Membership",
    "filled"
  >;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * uid field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: footer.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Background Image field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * small paragraph field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.small_paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  small_paragraph: prismic.RichTextField;

  /**
   * location field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Keep it in different lines
   * - **API ID Path**: footer.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;

  /**
   * email field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Links to Social field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links_to_social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_to_social: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryLinksToSocialItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Footer → Small → Primary*
 */
export interface FooterSliceSmallPrimary {
  /**
   * Links to Social field in *Footer → Small → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.small.primary.links_to_social[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links_to_social: prismic.GroupField<
    Simplify<FooterSliceSmallPrimaryLinksToSocialItem>
  >;
}

/**
 * Small variation for Footer Slice
 *
 * - **API ID**: `small`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceSmall = prismic.SharedSliceVariation<
  "small",
  Simplify<FooterSliceSmallPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault | FooterSliceSmall;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *GalleryOnHome → Default → Primary → Albums*
 */
export interface GalleryOnHomeSliceDefaultPrimaryAlbumsItem {
  /**
   * album field in *GalleryOnHome → Default → Primary → Albums*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_on_home.default.primary.albums[].album
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  album: prismic.ContentRelationshipField<"album">;
}

/**
 * Primary content in *GalleryOnHome → Default → Primary*
 */
export interface GalleryOnHomeSliceDefaultPrimary {
  /**
   * uid field in *GalleryOnHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: gallery_on_home.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Heading field in *GalleryOnHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_on_home.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Albums field in *GalleryOnHome → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_on_home.default.primary.albums[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  albums: prismic.GroupField<
    Simplify<GalleryOnHomeSliceDefaultPrimaryAlbumsItem>
  >;
}

/**
 * Default variation for GalleryOnHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryOnHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryOnHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryOnHome*
 */
type GalleryOnHomeSliceVariation = GalleryOnHomeSliceDefault;

/**
 * GalleryOnHome Shared Slice
 *
 * - **API ID**: `gallery_on_home`
 * - **Description**: GalleryOnHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryOnHomeSlice = prismic.SharedSlice<
  "gallery_on_home",
  GalleryOnHomeSliceVariation
>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Header Image field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.header_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * Title field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Info → Default → Primary*
 */
export interface InfoSliceDefaultPrimary {
  /**
   * uid field in *Info → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: info.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Heading field in *Info → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Info → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * bg_icon_pos field in *Info → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: info.default.primary.bg_icon_pos
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_icon_pos: prismic.SelectField<"left" | "right" | "none", "filled">;
}

/**
 * Default variation for Info Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Info → Imaged → Primary*
 */
export interface InfoSliceImagedPrimary {
  /**
   * uid field in *Info → Imaged → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: info.imaged.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Heading field in *Info → Imaged → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.imaged.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Info → Imaged → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info.imaged.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Image field in *Info → Imaged → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info.imaged.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Imaged variation for Info Slice
 *
 * - **API ID**: `imaged`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSliceImaged = prismic.SharedSliceVariation<
  "imaged",
  Simplify<InfoSliceImagedPrimary>,
  never
>;

/**
 * Slice variation for *Info*
 */
type InfoSliceVariation = InfoSliceDefault | InfoSliceImaged;

/**
 * Info Shared Slice
 *
 * - **API ID**: `info`
 * - **Description**: Info
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoSlice = prismic.SharedSlice<"info", InfoSliceVariation>;

/**
 * Item in *MerchPhotos → Default → Primary → photos*
 */
export interface MerchPhotosSliceDefaultPrimaryPhotosItem {
  /**
   * Image field in *MerchPhotos → Default → Primary → photos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: merch_photos.default.primary.photos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *MerchPhotos → Default → Primary*
 */
export interface MerchPhotosSliceDefaultPrimary {
  /**
   * uid field in *MerchPhotos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: NO SPACE/Use _ instead of space, and it will be replaced in production with space
   * - **API ID Path**: merch_photos.default.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;

  /**
   * Heading field in *MerchPhotos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: merch_photos.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * photos field in *MerchPhotos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: merch_photos.default.primary.photos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  photos: prismic.GroupField<
    Simplify<MerchPhotosSliceDefaultPrimaryPhotosItem>
  >;
}

/**
 * Default variation for MerchPhotos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MerchPhotosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MerchPhotosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MerchPhotos*
 */
type MerchPhotosSliceVariation = MerchPhotosSliceDefault;

/**
 * MerchPhotos Shared Slice
 *
 * - **API ID**: `merch_photos`
 * - **Description**: MerchPhotos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MerchPhotosSlice = prismic.SharedSlice<
  "merch_photos",
  MerchPhotosSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AlbumDocument,
      AlbumDocumentData,
      AlbumDocumentDataPhotosItem,
      ExecPageDocument,
      ExecPageDocumentData,
      ExecPageDocumentDataSlicesSlice,
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MerchDocument,
      MerchDocumentData,
      MerchDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataLinksToSocialItem,
      NavbarDocumentDataPagesItem,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      AlbumOnGallerySlice,
      AlbumOnGallerySliceDefaultPrimary,
      AlbumOnGallerySliceVariation,
      AlbumOnGallerySliceDefault,
      BigHeaderSlice,
      BigHeaderSliceDefaultPrimaryLinksToSocialItem,
      BigHeaderSliceDefaultPrimary,
      BigHeaderSliceVariation,
      BigHeaderSliceDefault,
      CalendarSlice,
      CalendarSliceDefaultPrimary,
      CalendarSliceVariation,
      CalendarSliceDefault,
      CoachingTeamSlice,
      CoachingTeamSliceDefaultPrimaryCoachesItem,
      CoachingTeamSliceDefaultPrimary,
      CoachingTeamSliceVariation,
      CoachingTeamSliceDefault,
      ExecPageSlice,
      ExecPageSliceDefaultPrimaryExecTeamItem,
      ExecPageSliceDefaultPrimary,
      ExecPageSliceVariation,
      ExecPageSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryLinksToSocialItem,
      FooterSliceDefaultPrimary,
      FooterSliceSmallPrimaryLinksToSocialItem,
      FooterSliceSmallPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      FooterSliceSmall,
      GalleryOnHomeSlice,
      GalleryOnHomeSliceDefaultPrimaryAlbumsItem,
      GalleryOnHomeSliceDefaultPrimary,
      GalleryOnHomeSliceVariation,
      GalleryOnHomeSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      InfoSlice,
      InfoSliceDefaultPrimary,
      InfoSliceImagedPrimary,
      InfoSliceVariation,
      InfoSliceDefault,
      InfoSliceImaged,
      MerchPhotosSlice,
      MerchPhotosSliceDefaultPrimaryPhotosItem,
      MerchPhotosSliceDefaultPrimary,
      MerchPhotosSliceVariation,
      MerchPhotosSliceDefault,
    };
  }
}
