import { Inter, Open_Sans } from "next/font/google";
import { clsx } from "clsx";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={clsx(inter.variable, openSans.variable)}>
      <body>
        {children}
      </body>
    </html>
  );
}
