// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  album_on_gallery: dynamic(() => import("./AlbumOnGallery")),
  big_header: dynamic(() => import("./Hero")),
  calendar: dynamic(() => import("./Calendar")),
  coaching_team: dynamic(() => import("./CoachingTeam")),
  exec_page: dynamic(() => import("./ExecTeam")),
  footer: dynamic(() => import("./Footer")),
  gallery_on_home: dynamic(() => import("./GalleryOnHome")),
  header: dynamic(() => import("./Header")),
  info: dynamic(() => import("./Info")),
};
