// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  big_header: dynamic(() => import("./Hero")),
  calendar: dynamic(() => import("./Calendar")),
  footer: dynamic(() => import("./Footer")),
  gallery_on_home: dynamic(() => import("./GalleryOnHome")),
  info: dynamic(() => import("./Info")),
};
